<a href="https://colab.research.google.com/github/tarvt/DeleSmell_SA_G5/blob/main/LoadModel.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
# load the model from disk
import pickle

filename = './drive/MyDrive/delesmell/delesmellmodel.sav'
delmodel = pickle.load(open(filename, 'rb'))

In [3]:
import pandas as pd
dataset_path = '/content/drive/MyDrive/delesmell/METHOD_01.csv'
df = pd.read_csv(dataset_path)
df.head()

,NAME,ALD,ATFD,CALIN,CC,CCL,CDISP,CEXT,CINT,CM,...,LOC,MAXNESTING,NOAV,NOEU,NOLV,NOP,word2vec,word2vec2,word2vec3,is_brain
0,tagDefineTextField,1,0,0,0,2,0.00,0,0,0,...,5,1,2,0,0,14,0.766091,0.295311,-0.482078,False
1,tagDefineFont2,1,0,1,0,2,0.00,0,0,0,...,6,1,3,0,0,13,0.350905,0.692511,0.782078,False
2,classifyStream,0,0,32,0,3,0.00,0,0,0,...,118,3,34,0,27,11,-0.064280,1.089711,2.046234,False
3,classifyStream,0,0,17,0,3,0.17,1,6,0,...,76,3,16,0,13,10,-0.479466,1.486911,3.310390,False
4,generate,0,0,22,0,3,0.00,0,0,0,...,131,3,37,0,20,9,-0.894651,1.884111,4.574546,False

In [4]:
df.drop('is_brain', inplace=True, axis=1)
df

,NAME,ALD,ATFD,CALIN,CC,CCL,CDISP,CEXT,CINT,CM,...,LAA,LOC,MAXNESTING,NOAV,NOEU,NOLV,NOP,word2vec,word2vec2,word2vec3
0,tagDefineTextField,1,0,0,0,2,0.00,0,0,0,...,1.0,5,1,2,0,0,14,0.766091,0.295311,-0.482078
1,tagDefineFont2,1,0,1,0,2,0.00,0,0,0,...,1.0,6,1,3,0,0,13,0.350905,0.692511,0.782078
2,classifyStream,0,0,32,0,3,0.00,0,0,0,...,1.0,118,3,34,0,27,11,-0.064280,1.089711,2.046234
3,classifyStream,0,0,17,0,3,0.17,1,6,0,...,1.0,76,3,16,0,13,10,-0.479466,1.486911,3.310390
4,generate,0,0,22,0,3,0.00,0,0,0,...,1.0,131,3,37,0,20,9,-0.894651,1.884111,4.574546
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
90310,testSchemaSourceSAX,0,0,0,0,1,0.00,0,0,0,...,1.0,16,2,3,0,3,0,0.914352,0.525572,2.288353
90311,testSchemaLanguageDOM,0,0,1,0,1,0.00,0,0,0,...,1.0,16,0,3,0,3,0,1.760695,-2.641099,4.957043
90312,testSchemaSourceDOM,0,0,0,0,1,0.00,0,0,0,...,1.0,19,2,3,0,4,0,-0.424762,2.243502,-4.415946
90313,printUsage,0,0,0,0,1,0.00,0,0,0,...,1.0,3,0,1,0,0,0,-7.071465,-9.756068,-7.683146
90314,PropertyTest,0,0,0,0,1,0.00,0,0,0,...,1.0,0,0,0,0,0,0,0.000479,-0.068491,0.002314

In [8]:
df.drop('NAME', inplace=True, axis=1)

In [15]:
predict_data = df.head(4)

In [16]:
predict_data = predict_data.values.reshape((predict_data.shape[0],predict_data.shape[1],1))

In [19]:
import numpy as np
index = np.argmax(delmodel.predict(predict_data), axis=-1)

1/1 [==============================] - 0s 43ms/step

In [20]:
index

array([0, 0, 0, 0])